#ifndef QKEEPALIVETCPSOCKET_GLOBAL_HPP
#define QKEEPALIVETCPSOCKET_GLOBAL_HPP

#include <QtCore/qglobal.h>

#if defined(QKEEPALIVETCPSOCKET_LIBRARY)
#  define QKEEPALIVETCPSOCKET_EXPORT Q_DECL_EXPORT
#else
#  define QKEEPALIVETCPSOCKET_EXPORT Q_DECL_IMPORT
#endif

#endif // QKEEPALIVETCPSOCKET_GLOBAL_HPP
